project:
  name: tinymaven
  version: 0.0.1
  mainClass: dev.markconley.tinymaven.TinyMaven
  packaging: jar # or "war"
  
dependencies:
  - group: org.yaml
    artifact: snakeyaml
    version: 2.2
  - group: commons-io
    artifact: commons-io
    version: 2.19.0

lifecycle:
  build:
    - clean
    - compile
    - testCompile
    - test
    - package
  verify:
    - compile
    - test

sourceDirectory: src/main/java
outputDirectory: build/classes
testSourceDirectory: src/test/java
testOutputDirectory: build/test-classes

